### ISSUE TITLE
fail to run

### ISSUE THREAD

**Issue by hexd2019** [lightjiao/vmess-to-clash#1]
Collecting requests
pip install PyYMAL

  Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x10382de90>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /simple/requests/
pip install flask

  Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x103314910>: Failed to establish a new connection: [Errno 8] nodename nor servname provided, or not known',)': /simple/requests/

**Comment by hexd2019** [comment]
good idea! but it can't work on my macos,so can you help me?

**Comment by hexd2019** [comment]
Could not fetch URL https://pypi.python.org/simple/requests/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661) - skipping
  Could not find a version that satisfies the requirement requests (from versions: )
No matching distribution found for requests

**Comment by lightjiao** [comment]
please check your internet or proxy.

Use proxy option at command line or pass environment variable for automatic use.
```
# export https_proxy=http://192.168.0.251:808
# export http_proxy=http://192.168.0.251:808
# pip install PyYAML
```
